using Sms.Domain.Audit;
using Sms.Domain.Common;

namespace Sms.Domain.Fees
{
    /// <summary>
    /// ppl.FeeCategory (doc/Modules/19 §7, BR-FEE-001): tuition, transport,
    /// books, uniform, registration, activity, exam, copy fees… VatRate is
    /// a fraction (0.15 = 15%), not a percentage integer, per DB doc's
    /// VatRateSnapshot convention (DECIMAL(6,4)); null = VAT-exempt.
    /// </summary>
    [Audited(AuditTier.T2)]
    public class FeeCategory : AuditableEntity, ISchoolScoped, ISoftActiveFiltered
    {
        public int SchoolId { get; set; }

        public string NameAr { get; set; } = string.Empty;

        public string NameEn { get; set; } = string.Empty;

        public decimal? VatRate { get; set; }

        public bool IsMandatory { get; set; }

        public bool IsRefundable { get; set; }

        /// <summary>BR-FEE-001: true = generated by a service assignment (transport route, book bundle) rather than a manual/registration trigger.</summary>
        public bool IsServiceLinked { get; set; }

        /// <summary>README Q9 GL export interface — a free-text mapping code, not a real GL integration.</summary>
        public string? GlExportCode { get; set; }

        public bool IsActive { get; set; } = true;
    }
}
